#ifndef TITRM_FONT_H
#define TITRM_FONT_H

#include <stdint.h>

#define TERM_GLYPH_W 5
#define TERM_GLYPH_H 7

/* Blank pixels between glyphs (horizontally) and between lines (vertically).
 * Setting TERM_LINE_GAP to 0 packs rows tighter (34 rows instead of 30), but
 * capitals and digits then touch the line above and below. */
#define TERM_CHAR_GAP 1
#ifndef TERM_LINE_GAP
#define TERM_LINE_GAP 1
#endif

#define TERM_CELL_W (TERM_GLYPH_W + TERM_CHAR_GAP)
#define TERM_CELL_H (TERM_GLYPH_H + TERM_LINE_GAP)

#define TERM_SCREEN_W 320
#define TERM_SCREEN_H 240

/* Grid size, derived from the glyph size and the screen size. */
#define TERM_COLS (TERM_SCREEN_W / TERM_CELL_W)
#define TERM_ROWS (TERM_SCREEN_H / TERM_CELL_H)

typedef struct {
    uint8_t rows[TERM_GLYPH_H]; /* one byte per row, bits 4..0 = pixels left to right */
} term_glyph_t;

/* Generated by tools/gen_font.py; see FONT.md for the code -> glyph map. */
extern const term_glyph_t term_font[256];

#endif
