/* GENERATED by tools/gen_font.py. Do not edit. */
#ifndef TITRM_CHARS_H
#define TITRM_CHARS_H

/* Glyphs in the reserved 0x80-0xFF range. See FONT.md for the full table. */
#define TERM_CH_HLINE      0x80
#define TERM_CH_VLINE      0x81
#define TERM_CH_TL         0x82
#define TERM_CH_TR         0x83
#define TERM_CH_BL         0x84
#define TERM_CH_BR         0x85
#define TERM_CH_LTEE       0x86
#define TERM_CH_RTEE       0x87
#define TERM_CH_TTEE       0x88
#define TERM_CH_BTEE       0x89
#define TERM_CH_CROSS      0x8A
#define TERM_CH_CHECK      0x90
#define TERM_CH_CROSSMARK  0x91
#define TERM_CH_DOT        0x92
#define TERM_CH_DOT_EMPTY  0x93
#define TERM_CH_ARROW_R    0x94
#define TERM_CH_ARROW_D    0x95
#define TERM_CH_ARROW_U    0x96
#define TERM_CH_SIG0       0x98
#define TERM_CH_SIG1       0x99
#define TERM_CH_SIG2       0x9A
#define TERM_CH_SIG3       0x9B
#define TERM_CH_SHADE      0x9C
#define TERM_CH_SMILE      0x9D
#define TERM_CH_BLOCK      0x9E

/* The same glyphs as string literals, for building text:
 *   TERM_S_CHECK "Done"  ->  "\x90" "Done"
 * (adjacent literals concatenate after escapes are processed, so a
 * following hex digit can't be swallowed into the escape.) */
#define TERM_S_HLINE      "\x80"
#define TERM_S_VLINE      "\x81"
#define TERM_S_TL         "\x82"
#define TERM_S_TR         "\x83"
#define TERM_S_BL         "\x84"
#define TERM_S_BR         "\x85"
#define TERM_S_LTEE       "\x86"
#define TERM_S_RTEE       "\x87"
#define TERM_S_TTEE       "\x88"
#define TERM_S_BTEE       "\x89"
#define TERM_S_CROSS      "\x8A"
#define TERM_S_CHECK      "\x90"
#define TERM_S_CROSSMARK  "\x91"
#define TERM_S_DOT        "\x92"
#define TERM_S_DOT_EMPTY  "\x93"
#define TERM_S_ARROW_R    "\x94"
#define TERM_S_ARROW_D    "\x95"
#define TERM_S_ARROW_U    "\x96"
#define TERM_S_SIG0       "\x98"
#define TERM_S_SIG1       "\x99"
#define TERM_S_SIG2       "\x9A"
#define TERM_S_SIG3       "\x9B"
#define TERM_S_SHADE      "\x9C"
#define TERM_S_SMILE      "\x9D"
#define TERM_S_BLOCK      "\x9E"

#endif
