# ----------------------------
# Makefile Options
# ----------------------------

NAME = TITRMTST
ICON =
DESCRIPTION = "titrmlib basic test"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz -I../../src
CXXFLAGS = -Wall -Wextra -Oz -I../../src

EXTRA_C_SOURCES = $(wildcard ../../src/*.c)
EXTRA_HEADERS = $(wildcard ../../src/*.h)

BINDIR = ../../bin/basic

# ----------------------------

include $(shell cedev-config --makefile)
