name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up CE C/C++ toolchain
        uses: gavinhsmith/setup-ti84-ce-toolchain@v1.0.0

      - name: Build
        run: make
